apiVersion: v1
kind: Service
metadata:
  name: {{ include "ws1scimadapter.fullname" . }}
  labels:
    {{- include "ws1scimadapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: poolservice
      protocol: TCP
      name: virtualservice
  selector:
    {{- include "ws1scimadapter.selectorLabels" . | nindent 4 }}
